### PR TITLE
Update addTwoHugeNumbers.py

### PR DESCRIPTION
**Pull request by elemanhillary-zz**
its far more better than the previous which would throw an **AttributeError**

### CODE REVIEW

**Review by dvitsios — COMMENTED** [review]
The problem is supposed to be solved with linked lists, not arrays/python lists. The definition of the list node  Class is:

```
class ListNode(object):
    def __init__(self, x):
        self.value = x
        self.next = None
```

So, you need to construct these linked lists before running the script. 
For input values: a = [123, 4, 5] and b = [100, 100, 100]

you can construct them e.g. like that:

```
a = ListNode(123)
a.next = ListNode(4)
a.next.next = ListNode(5)
a.next.next.next = None

b = ListNode(100)
b.next = ListNode(100)
b.next.next = ListNode(100)
b.next.next.next = None
```

Additionally, your solution doesn't take into account the leading zeros that each number within a linked list may have.

**Comment by elemanhillary-zz** [comment]
it perfectly works and it was a success in codefights

**Comment by dvitsios** [comment]
I tried your code on codefights too but it's not working I'm afraid. 
Even if it were though, the point of this task is to get you familiarised with linked lists.

If you get asked in a an interview to provide a solution using linked lists you simply can't use a python list. You need instead a data structure that has nodes with values and pointers to next nodes etc., aka a linked list implementation. Hope that helps.

**Comment by elemanhillary-zz** [comment]
ok bro thanks for the lecture i appreciate **closed**

**Pull request closed without merging**
